# -*- mode: ruby -*-
# vi: set ft=ruby :

# Boxes to build a baseline Triple0 deployment

Vagrant.configure(2) do |config|
  # Create UnderCloud Servers
  (1..2).each do |i|
    config.vm.define "triple0#{i}" do |node|
        node.vm.box = "centos/7"
        node.vm.hostname = "triple0#{i}"
        node.vm.network :private_network, ip: "10.20.30.1#{i}"
        node.vm.network :private_network, ip: "192.168.11.1#{i}"
        node.vm.network :private_network, ip: "172.168.10.1#{i}"
#        node.vm.network "forwarded_port", guest: 80, host: 31480
        node.vm.provider "libvirt" do |vb|
          vb.memory = "2048"
        end
    end
  end

end
