# -*- mode: ruby -*-
# vi: set ft=ruby :

# Boxes to build a baseline Triple0 deployment

Vagrant.configure(2) do |config|
  # Create some PXE Servers
  (1..3).each do |i|
    config.vm.define "opxe#{i}" do |pxe|
      pxe.vm.network :private_network, ip: "10.0.2.8#{i}"
      pxe.vm.network :private_network, ip: "10.0.4.8#{i}"
      pxe.vm.network :private_network, ip: "10.0.6.8#{i}"
      pxe.vm.network :private_network, ip: "10.0.10.8#{i}"
      pxe.vm.network :public_network, :dev => "br-pxe", :mode => "bridge", :type => "bridge", ip: "10.1.2.20#{i}"      
      pxe.vm.provider :libvirt do |domain|
        domain.storage :file, :size => '100G', :type => 'qcow2'
        domain.boot 'network'
        domain.boot 'hd'
        domain.memory = "4096"
        domain.cpus = "1"
        domain.nested = "true"
      end
    end
  end
  # Create some PXE Servers
  (1..2).each do |i|
    config.vm.define "cpxe#{i}" do |pxe|
      pxe.vm.network :private_network, ip: "10.0.2.9#{i}"
      pxe.vm.network :private_network, ip: "10.0.4.9#{i}"
      pxe.vm.network :private_network, ip: "10.0.6.9#{i}"
      pxe.vm.network :private_network, ip: "10.0.10.9#{i}"
      pxe.vm.network :public_network, :dev => "br-pxe", :mode => "bridge", :type => "bridge", ip: "10.1.2.21#{i}"
      pxe.vm.provider :libvirt do |domain|
        domain.storage :file, :size => '100G', :type => 'qcow2'
        domain.boot 'network'
        domain.boot 'hd'
        domain.memory = "8192"
        domain.cpus = "1"
        domain.nested = "true"
      end
    end
  end
end

