# -*- mode: ruby -*-
# vi: set ft=ruby :

# Boxes to build a baseline Triple0 deployment

Vagrant.configure(2) do |config|
  # Create an OverCloud Servers
  (1..3).each do |i|
    config.vm.define "controller0#{i}" do |rdo|
        rdo.vm.box = "centos/7"
        rdo.vm.hostname = "controller0#{i}"
        rdo.vm.network :private_network, ip: "10.0.0.1#{i}"
        rdo.vm.network :private_network, ip: "10.0.2.1#{i}"
        rdo.vm.network :private_network, ip: "10.0.4.1#{i}"
        rdo.vm.network :private_network, ip: "10.0.6.1#{i}"
        rdo.vm.network :private_network, ip: "10.0.10.1#{i}"
        rdo.vm.network :public_network, :dev => "br-ex", :mode => "bridge", :type => "bridge"
        rdo.vm.network :public_network, :dev => "br-int", :mode => "bridge", :type => "bridge"
        rdo.vm.network :public_network, :dev => "br-pxe", :mode => "bridge", :type => "bridge"
#        rdo.vm.network "forwarded_port", guest: 80, host: 31480
        rdo.vm.provider "libvirt" do |vb|
          vb.memory = "4096"
          vb.cpus = "2"

        end
        rdo.vm.provision :shell, path: "../bootstrp-bash.sh"
        rdo.vm.provision :shell, path: "../bootstrp-common.sh"
#        rdo.vm.provision :shell, path: "bootstrp-rdo.sh"
    end
  end

  # Create OverCLoud Compute Nodes for OpenStack
  (1..4).each do |i|
    config.vm.define "compute0#{i}" do |compute|
        compute.vm.box = "centos/7"
        compute.vm.hostname = "compute0#{i}"
        compute.vm.network :private_network, ip: "10.0.0.2#{i}"
        compute.vm.network :private_network, ip: "10.0.2.2#{i}"
        compute.vm.network :private_network, ip: "10.0.4.2#{i}"
        compute.vm.network :private_network, ip: "10.0.6.2#{i}"
        compute.vm.network :private_network, ip: "10.0.10.0#{i}"
        compute.vm.network :public_network, :dev => "br-ex", :mode => "bridge", :type => "bridge"
        compute.vm.network :public_network, :dev => "br-int", :mode => "bridge", :type => "bridge"
        compute.vm.network :public_network, :dev => "br-pxe", :mode => "bridge", :type => "bridge"
#        compute.vm.network "forwarded_port", guest: 80, host: 31480
        compute.vm.provider "libvirt" do |vb|
          vb.memory = "8192"
          vb.cpus = "2"
          vb.nested = "true"
        end
        compute.vm.provision :shell, path: "../bootstrp-bash.sh"
        compute.vm.provision :shell, path: "../bootstrp-common.sh"
    end
  end


end
