# -*- mode: ruby -*-
# vi: set ft=ruby :

# Boxes to build a baseline Triple0 deployment

Vagrant.configure(2) do |config|
  # Create UnderCloud Servers
  (1..3).each do |i|
    config.vm.define "ooo0#{i}" do |under|
    if Vagrant.has_plugin?("vagrant-cachier")
      config.cache.scope = :box
        end
        under.vm.box = "centos/7"
        under.vm.hostname = "ooo0#{i}"
        under.vm.network :public_network, :dev => "br-ex", :mode => "bridge", :type => "bridge"
        under.vm.network :public_network, :dev => "br-int", :mode => "bridge", :type => "bridge"
        under.vm.network :private_network, ip: "10.0.0.1#{i}"
        under.vm.network :private_network, ip: "10.0.2.1#{i}"
        under.vm.network "forwarded_port", guest: 80, host: "800#{i}"
        #Size the libvirt VM
        under.vm.provider "libvirt" do |vb|
          vb.memory = "12288"
          vb.cpus = "4"
          vb.nested = "true"
        end
        under.vm.provision :shell, path: "../bootstrp-bash.sh"
    end
  end

  (1..4).each do |i|
    config.vm.define "pxe#{i}" do |pxe|
      pxe.vm.network :private_network, ip: "10.0.2.2#{i}"
      pxe.vm.network :private_network, ip: "10.0.4.2#{i}"
      pxe.vm.network :private_network, ip: "10.0.6.2#{i}"
      pxe.vm.network :private_network, ip: "10.0.8.2#{i}"
      pxe.vm.network :private_network, ip: "10.0.10.2#{i}"
      pxe.vm.network :public_network, :dev => "br-int", :mode => "bridge", :type => "bridge"
      pxe.vm.provider :libvirt do |domain|
        domain.storage :file, :size => '100G', :type => 'qcow2'
        domain.boot 'network'
        domain.boot 'hd'
        domain.memory = "8192"
        domain.cpus = "1"
        domain.nested = "true"
      end
    end
  end
end
