# -*- mode: ruby -*-
# vi: set ft=ruby :

# Boxes to build a baseline Triple0 deployment

Vagrant.configure(2) do |config|
  # Create an OverCloud Servers
  (1..1).each do |i|
    config.vm.define "controller0#{i}" do |rdo|
        rdo.vm.box = "centos/7"
        rdo.vm.hostname = "controller0#{i}"
        rdo.vm.network :public_network, :dev => "br-ex", :mode => "bridge", :type => "bridge"
        rdo.vm.network :public_network, :dev => "br-int", :mode => "bridge", :type => "bridge"
#        rdo.vm.network "forwarded_port", guest: 80, host: 31480
        rdo.vm.provider "libvirt" do |vb|
          vb.memory = "8192"
          vb.cpus = "4"

        end
        rdo.vm.provision :shell, path: "../bootstrp-bash.sh"
        rdo.vm.provision :shell, path: "bootstrp-rdo.sh"
    end
  end

end
