# -*- mode: ruby -*-
# vi: set ft=ruby :

# Boxes to build a baseline Triple0 deployment

Vagrant.configure(2) do |config|
  # Create UnderCloud Servers
  (1..1).each do |i|
    config.vm.define "ooo0#{i}" do |under|
        under.vm.box = "centos/7"
        under.vm.hostname = "ooo0#{i}"
       # Network Configuration
        under.vm.network :private_network, ip: "10.0.0.0#{i}"
        under.vm.network :public_network, :dev => "br-int", :mode => "bridge", :type => "bridge"
        under.vm.network :public_network, :dev => "br-pxe", :mode => "bridge", :type => "bridge"
       # Port forwarding
        under.vm.network "forwarded_port", guest: 80, host: "808#{i}"
       # CPU and Memory
        under.vm.provider "libvirt" do |vb|
          vb.memory = "8192"
          vb.cpus = "2"
          vb.nested = "true"
        end
    end
  end
end
