# -*- mode: ruby -*-
# vi: set ft=ruby :

# Boxes to build a baseline Triple0 deployment

Vagrant.configure(2) do |config|
  # Create an OverCloud Servers
  (1..4).each do |i|
    config.vm.define "ceph0#{i}" do |ceph|
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.cache.scope = :box
        ceph.vm.box = "centos/7"
        ceph.vm.hostname = "ceph0#{i}"
        ceph.vm.network :public_network, :dev => "br-ex", :mode => "bridge", :type => "bridge"
        ceph.vm.network :public_network, :dev => "br-int", :mode => "bridge", :type => "bridge", :ip => "192.168.10.15#{i}"
#        ceph.vm.network "forwarded_port", guest: 80, host: 31480
        ceph.vm.provider "libvirt" do |vb|
          vb.memory = "3096"
          vb.cpus = "1"
          vb.storage :file, :size => '20G', :type => 'raw'
          vb.storage :file, :size => '20G', :type => 'raw'
        end
        ceph.vm.provision :shell, path: "../bootstrp-bash.sh"
        ceph.vm.provision :shell, path: "bootstrp-ceph.sh"
    end
  end

end
