# configure rsyslog on controller nodes
---
- hosts: controllers
  remote_user: heat-admin
  connection: ssh
  become: yes
  become_method: sudo
  vars:
  tasks:
  - name: Check if rsyslog is installed
    yum: pkg=rsyslog state=installed update_cache=True
  
