--- # Install TripleO undercloud
- hosts: TripleO
  remote_user: vagrant
  become: yes
  become_method: sudo
  connection: ssh
  vars:
    DIB_INSTALLTYPE_puppet_modules:
      DIB_INSTALLTYPE_puppet_modules: source

  tasks:
    - name: Install epel-release and update repo
      yum: pkg=epel-release state=latest update_cache=yum
      environment={{ DIB_INSTALLTYPE_puppet_modules }}

    - name: Get
      get_url: dest=http://buildlogs.centos.org/centos/7/cloud/x86_64/rdo-trunk-master-tripleo/delorean.repo
               src=/etc/yum.repos.d/delorean.repo
               mode=0777

    - name: Get
      get_url: dest=http://trunk.rdoproject.org/centos7/delorean-deps.repo
               src=/etc/yum.repos.d/delorean-deps.repo
               mode=0777

    - name: Get
      get_url: dest=http://trunk.rdoproject.org/centos7/current/delorean.repo
               src=/etc/yum.repos.d/delorean-current.repo
               mode=0777

    - name: Install Yum Plugin Priorities and Python Triple O Client
      yum: pkg={{ item }} state=latest update_cache=yum
      with_items:
        - yum-plugin-priorities
        - python-tripleoclient

    - name: Copy config template
      file: src=/usr/share/instack-undercloud/undercloud.conf.sample
            dest=~/undercloud.conf
            owner=vagrant
            group=vagrant
            mode=0777
