
--- # Install All-in-One Packstack
- hosts: rdo
  remote_user: vagrant
  become: yes
  become_method: sudo
  connection: ssh
  tasks: 
  - name: Disable Network Manager, Enable Network, Disable FirewallD
    shell: systemctl disable firewalld && systemctl stop firewalld && \
           systemctl disable NetworkManager && systemctl stop NetworkManager && \
           systemctl enable network && systemctl start network
  - name: Update YUM
    yum: update_cache=yes
  - name: Install OpenStack
    yum: pkg=centos-release-openstack-mitaka state=installed
  - name: Update Yum
    yum: update_cache=yes
  - name: install PackStack
    shell: packstack --allinone

# systemctl disable firewalld
# systemctl stop firewalld
# systemctl disable NetworkManager
# systemctl stop NetworkManager
# systemctl enable network
# systemctl start network
# yum update
# yum install -y centos-release-openstack-mitaka
# yum update -y
# yum install -y openstack-packstack
# packstack --allinone

