--- # This is a playbook that will install the undercloud
- hosts: undercloud
  become: yes
  become_method: sudo
  connection: ssh
  tasks:
  - name: Install dependencies 
    yum: pkg={{ item }} state=present update_cache=yes
    with_items:
       - yum-utils
       - epel-release
       - yum-plugin-priorities
       - python-tripleoclient
  - name: Pull RDO Delorean trunk
    shell: curl -L -o /etc/yum.repos.d/delorean.repo http://buildlogs.centos.org/centos/7/cloud/x86_64/rdo-trunk-master-tripleo/delorean.repo

  - name: Pull RDO depdencies
    shell: curl -L -o /etc/yum.repos.d/delorean-deps.repo http://trunk.rdoproject.org/centos7/delorean-deps.repo


