--- # Install TripleO undercloud
- hosts: undercloud
  remote_user: vagrant
  become: yes
  become_method: sudo
  connection: ssh
  vars:
    user: vagrant
    user_group: vagrant
    # Certificate vars for the cacert.pem
    country: US
    state: Arizona
    location: Peoria
    CN: triple.ooo2

  tasks:
    - name: Install epel-release and update repo
      yum: pkg=epel-release state=latest update_cache=yes

#    - name: Get Delorean Repo
#      get_url: url=http://buildlogs.centos.org/centos/7/cloud/x86_64/rdo-trunk-master-tripleo/delorean.repo
#               dest=/etc/yum.repos.d/delorean.repo
#               mode=0777

    - name: Get Delorean Depedencies Repo
      get_url: url=http://trunk.rdoproject.org/centos7/delorean-deps.repo
               dest=/etc/yum.repos.d/delorean-deps.repo
               mode=0777

    - name: Get Delorea Current
      get_url: url=http://trunk.rdoproject.org/centos7/current/delorean.repo
               dest=/etc/yum.repos.d/delorean-current.repo
               mode=0777

    - name: Install Yum Plugin Priorities and Python Triple O Client
      yum: pkg={{ item }} state=latest update_cache=yes
      with_items:
        - yum-plugin-priorities
        - python-tripleoclient

    - name: Create undercloud.conf
      file: dest=/home/vagrant/undercloud.conf state=touch

    - name: Copy config template
      file: src=/usr/share/instack-undercloud/undercloud.conf.sample
            dest=/home/vagrant/undercloud.conf
            state=file
            owner={{ user }}
            group={{ user_group }}
            mode=0777

    - name: Define ENV Variable
      shell: export DIB_INSTALLTYPE_puppet_modules=source

    - name: Create Certificate
      shell: openssl genrsa -out privkey.pem 2048

    - name: Create cacert.pem
      shell: openssl req \
             -new \
             -x509 \
             -key privkey.pem \
             -days 365 \
             -subj "/C={{ country }}/ST={{ state }}/L={{ location }}/O=Dis/CN={{ CN }}" \
             -out cacert.pem
    - name: Create undercloud.pem
      shell: cat cacert.pem privkey.pem > undercloud.pem

    - name: Update undercloud.pem ownership
      file: dest=/home/vagrant/undercloud.pem owner={{ user }} group={{ user_group }} state=file

    - name: Create /etc/pki/instack-certs
      file: dest=/etc/pki/instack-certs state=directory

    - name: Touch undercloud.pem
      file: dest=/etc/pki/instack-certs/undercloud.pem
            state=touch

    - name: Import undercloud.pem
      file: src=/home/vagrant/undercloud.pem
            dest=/etc/pki/instack-certs/undercloud.pem
            state=file
            mode=0600

    - name: Update SEManage
      shell: semanage fcontext -a -t etc_t "/etc/pki/instack-certs(/.*)?"

    - name: Restorecon to instack-certs
      shell: restorecon -R /etc/pki/instack-certs

    - name: Touch cacert.pem
      file: dest=/etc/pki/ca-trust/source/anchors/cacert.pem
            state=touch

    - name: Import cacert.pem
      file: src=/home/vagrant/cacert.pem
            dest=/etc/pki/ca-trust/source/anchors/cacert.pem
            state=file
            mode=0600

    - name: Update CA Trust
      shell: update-ca-trust extract
