resource_registry:
 OS::TripleO::BlockStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/cinder-storage.yaml
 OS::TripleO::Compute::Net::SoftwareConfig: /home/stack/templates/nic-configs/compute.yaml
 OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/templates/nic-configs/controller.yaml
 OS::TripleO::ObjectStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/swift-storage.yaml

parameter_defaults:

 # The IP address of the EC2 metadata server. Generally the IP of the Undercloud
 EC2MetadataIp: 10.0.0.2
 # Gateway router for the provisioning network (or Undercloud IP)
 ControlPlaneDefaultRoute: 10.0.0.2
 # https://bugzilla.redhat.com/show_bug.cgi?id=1328149
 ControlPlaneSubnetCidr: '24'
 DnsServers: ["8.8.8.8"]

 InternalApiNetCidr: 10.0.2.0/24
 TenantNetCidr: 10.0.6.0/24
 StorageNetCidr: 10.0.4.0/24
 StorageMgmtNetCidr: 10.0.10.0/24
 ExternalNetCidr: 64.106.198.128/27

 # Leave room for floating IPs in the External allocation pool
 ExternalAllocationPools: [{'start': '64.106.198.129', 'end': '64.106.198.158'}]
 InternalApiAllocationPools: [{'start': '10.0.2.100', 'end': '10.0.2.200'}]
 TenantAllocationPools: [{'start': '10.0.6.10', 'end': '10.0.6.200'}]
 StorageAllocationPools: [{'start': '10.0.4.10', 'end': '10.0.4.200'}]
 StorageMgmtAllocationPools: [{'start': '10.0.10.100', 'end': '10.0.10.200'}]

 InternalApiNetworkVlanID: 201
 StorageNetworkVlanID: 202
 StorageMgmtNetworkVlanID: 203
 TenantNetworkVlanID: 204

 # ExternalNetworkVlanID: 100
 # Set to the router gateway on the external network
 ExternalInterfaceDefaultRoute: 192.168.100.1
 # Set to "br-ex" if using floating IPs on native VLAN on bridge br-ex
 NeutronExternalNetworkBridge: "br-ex"

 # Customize bonding options if required
 BondInterfaceOvsOptions: "bond_mode=active-backup"
