---
- hosts: logging
  remote_user: heat-admin
  connection: ssh
  become: yes
  become_method: sudo
  vars:
  tasks:
  - name: Check if rsyslog is installed on controller nodes
    yum: pkg=rsyslog state=installed

  tasks:
    - name: Update rsyslog.conf
      blockinfile: |
        dest=/etc/rsyslog.conf backup=yes
        content='$template TmplMsg, "/var/log/%HOSTNAME%/%PROGRAMNAME%.log"
        $template TmplAuth, "/var/log/%HOSTNAME%/%PROGRAMNAME%.log"
        authpriv.*   ?TmplAuth
        *.info,mail.none,authpriv.none,cron.none   ?TmplMsg'
      notify: Restart rsyslog
  handlers:
    - name: Restart rsyslog
      shell: systemctl restart rsyslog

