# -*- mode: ruby -*-
# vi: set ft=ruby :

# Boxes to build a baseline Triple0 deployment

Vagrant.configure(2) do |config|
  # Create UnderCloud Servers
  (1..1).each do |i|
    config.vm.define "tripleo#{i}" do |node|
        node.vm.box = "centos/7"
        node.vm.hostname = "tripleo#{i}"
        node.vm.network :private_network, ip: "10.0.0.0#{i}"
        node.vm.network :private_network, ip: "10.0.2.0#{i}"
        node.vm.network :private_network, ip: "10.0.4.0#{i}"
        node.vm.network :private_network, ip: "10.0.10.0#{i}"
#        node.vm.network "forwarded_port", guest: 80, host: 31480
        node.vm.provider "libvirt" do |vb|
          vb.memory = "4096"
        end
        node.vm.provision :shell, path: "bootstrp-ooo.sh"
    end
  end

  # Create an OverCloud Servers
  (1..3).each do |i|
    config.vm.define "rdo0#{i}" do |node|
        node.vm.box = "centos/7"
        node.vm.hostname = "rdo0#{i}"
        node.vm.network :private_network, ip: "10.0.0.1#{i}"
        node.vm.network :private_network, ip: "10.0.2.1#{i}"
        node.vm.network :private_network, ip: "10.0.4.1#{i}"
        node.vm.network :private_network, ip: "10.0.6.1#{i}"
        node.vm.network :private_network, ip: "10.0.10.1#{i}"
#        node.vm.network "forwarded_port", guest: 80, host: 31480
        node.vm.provider "libvirt" do |vb|
          vb.memory = "2048"

        end
    end
  end
 
  # Create Compute Nodes for OpenStack
  (1..2).each do |i|
    config.vm.define "compute0#{i}" do |node|
        node.vm.box = "centos/7"
        node.vm.hostname = "compute0#{i}"
        node.vm.network :private_network, ip: "10.0.0.2#{i}"
        node.vm.network :private_network, ip: "10.0.2.2#{i}"
        node.vm.network :private_network, ip: "10.0.4.2#{i}"
        node.vm.network :private_network, ip: "10.0.6.2#{i}"
        node.vm.network :private_network, ip: "10.0.10.0#{i}"
#        node.vm.network "forwarded_port", guest: 80, host: 31480
        node.vm.provider "libvirt" do |vb|
          vb.memory = "4096"

        end
        node.vm.provision :shell, path: "bootstrp-compute.sh"
    end
  end

  # Create Database Nodes for MariaDB
  (1..1).each do |i|
    config.vm.define "maria0#{i}" do |node|
        node.vm.box = "centos/7"
        node.vm.hostname = "maria0#{i}"
        node.vm.network :private_network, ip: "10.0.0.3#{i}"
        node.vm.network :private_network, ip: "10.0.2.3#{i}"
#        node.vm.network "forwarded_port", guest: 80, host: 31480
        node.vm.provider "libvirt" do |vb|
          vb.memory = "4096"

        end
    end
  end

  # Create an Ansible Server
  (1..1).each do |i|
    config.vm.define "ansible0#{i}" do |acs|
        acs.vm.box = "yk0/ubuntu-xenial"
        acs.vm.hostname = "ansible0#{i}"
        acs.vm.network :private_network, ip: "10.0.0.4#{i}"
#        acs.vm.network "forwarded_port", guest: 80, host: 31480
        acs.vm.provider "libvirt" do |vb|
          vb.memory = "2048"

        end
        acs.vm.provision :shell, path: "bootstrp-ansible.sh"
    end
  end


end
