# -*- mode: ruby -*-
# vi: set ft=ruby :

# Boxes to build a baseline Triple0 deployment

Vagrant.configure(2) do |config|
  # Create UnderCloud Servers
  (1..1).each do |i|
    config.vm.define "ooo0#{i}" do |under|
        under.vm.box = "centos/7"
        under.vm.hostname = "ooo0#{i}"
        under.vm.network :private_network, ip: "10.0.0.0#{i}"
        under.vm.network :private_network, ip: "10.0.2.0#{i}"
        under.vm.network :private_network, ip: "10.0.4.0#{i}"
        under.vm.network :private_network, ip: "10.0.10.0#{i}"
#        node.vm.network "forwarded_port", guest: 80, host: 31480
        under.vm.provider "libvirt" do |vb|
          vb.memory = "2048"
        end
        under.vm.provision :shell, path: "bootstrp-common.sh"
        under.vm.provision :shell, path: "bootstrp-ooo.sh"
    end
  end

  # Create an OverCloud Servers
  (1..1).each do |i|
    config.vm.define "rdo0#{i}" do |rdo|
        rdo.vm.box = "centos/7"
        rdo.vm.hostname = "rdo0#{i}"
        rdo.vm.network :private_network, ip: "10.0.0.1#{i}"
        rdo.vm.network :private_network, ip: "10.0.2.1#{i}"
        rdo.vm.network :private_network, ip: "10.0.4.1#{i}"
        rdo.vm.network :private_network, ip: "10.0.6.1#{i}"
        rdo.vm.network :private_network, ip: "10.0.10.1#{i}"
#        rdo.vm.network "forwarded_port", guest: 80, host: 31480
        rdo.vm.provider "libvirt" do |vb|
          vb.memory = "2048"

        end
        rdo.vm.provision :shell, path: "bootstrp-common.sh"
        rdo.vm.provision :shell, path: "bootstrp-rdo.sh"
    end
  end

  # Create OverCLoud Compute Nodes for OpenStack
  (1..1).each do |i|
    config.vm.define "compute0#{i}" do |compute|
        compute.vm.box = "centos/7"
        compute.vm.hostname = "compute0#{i}"
        compute.vm.network :private_network, ip: "10.0.0.2#{i}"
        compute.vm.network :private_network, ip: "10.0.2.2#{i}"
        compute.vm.network :private_network, ip: "10.0.4.2#{i}"
        compute.vm.network :private_network, ip: "10.0.6.2#{i}"
        compute.vm.network :private_network, ip: "10.0.10.0#{i}"
#        compute.vm.network "forwarded_port", guest: 80, host: 31480
        compute.vm.provider "libvirt" do |vb|
          vb.memory = "4096"

        end
        compute.vm.provision :shell, path: "bootstrp-common.sh"
        compute.vm.provision :shell, path: "bootstrp-compute.sh"
    end
  end

  # Create Database Nodes for MariaDB
  (1..1).each do |i|
    config.vm.define "maria0#{i}" do |maria|
        maria.vm.box = "centos/7"
        maria.vm.hostname = "maria0#{i}"
        maria.vm.network :private_network, ip: "10.0.0.3#{i}"
        maria.vm.network :private_network, ip: "10.0.2.3#{i}"
#        node.vm.network "forwarded_port", guest: 80, host: 31480
        maria.vm.provider "libvirt" do |vb|
          vb.memory = "4096"

        end
        maria.vm.provision :shell, path: "bootstrp-common.sh"
        maria.vm.provision :shell, path: "bootstrp-maria.sh"
    end
  end

  # Create an Ansible Server
  (1..1).each do |i|
    config.vm.define "ansible0#{i}" do |acs|
        acs.vm.box = "yk0/ubuntu-xenial"
        acs.vm.hostname = "ansible0#{i}"
        acs.vm.network :private_network, ip: "10.0.0.4#{i}"
#        acs.vm.network "forwarded_port", guest: 80, host: 31480
        acs.vm.provider "libvirt" do |vb|
          vb.memory = "2048"

        end
        acs.vm.provision :shell, path: "bootstrp-common.sh"
        acs.vm.provision :shell, path: "bootstrp-ansible.sh"
    end
  end

  # Create Database Nodes for MariaDB
  (1..1).each do |i|
    config.vm.define "docker0#{i}" do |docker|
        docker.vm.box = "yk0/ubuntu-xenial"
        docker.vm.hostname = "docker0#{i}"
        docker.vm.network :private_network, ip: "10.0.0.5#{i}"
        docker.vm.network :private_network, ip: "10.0.2.5#{i}"
#        docker.vm.network "forwarded_port", guest: 80, host: 31480
        docker.vm.provider "libvirt" do |vb|
          vb.memory = "4096"

        end
        docker.vm.provision :shell, path: "bootstrp-common.sh"
        docker.vm.provision :shell, path: "bootstrp-docker.sh"
    end
  end

end
